"""empty message

Revision ID: 3c72fd04ca75
Revises: b41804420367
Create Date: 2022-07-28 17:17:50.195307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72fd04ca75'
down_revision = 'b41804420367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('massistants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('massistant', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mofficers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mofficer', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pakars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pakar', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snurses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snurse', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snurses')
    op.drop_table('pakars')
    op.drop_table('mofficers')
    op.drop_table('massistants')
    op.drop_table('drivers')
    # ### end Alembic commands ###
